### ISSUE TITLE
Bonus stage: calculation for non-rectangular rooms

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/FlooringCalculator#3]
Implement an additional shape for the calculation that is not a rectangle

**Comment by geordzNZ** [comment]
Havent closed this one off yet, as think there will be some feedback on it...

Have assumed that users will enter the correct values for floorShape, hope that is OK (for now)?

What is C Sharp best practice around declaring of variables ... at the start of the function, or inline with code as they are needed?... as I have done both here

**Comment by incredibleLeitman** [comment]
I think that the basic functionality of this issue is implemented, so you can close it 👍 
For refactoring and other feedback I will open up new issues.

I think inline variables are the most common variant in C#, declare variables where you use them. Having all on top of your function is more classic C style.

**Comment by geordzNZ** [comment]
OK noted, thanks!
