### ISSUE TITLE
multiple conditions that check the same thing

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/FlooringCalculator#5]
https://github.com/geordzNZ/FlooringCalculator/blob/e3beb5065c953d095e8691ed1299bff03679eeea/FlooringCalculator/Program.cs#L32-L43
https://github.com/geordzNZ/FlooringCalculator/blob/e3beb5065c953d095e8691ed1299bff03679eeea/FlooringCalculator/Program.cs#L50-L57
https://github.com/geordzNZ/FlooringCalculator/blob/e3beb5065c953d095e8691ed1299bff03679eeea/FlooringCalculator/Program.cs#L60-L68
https://github.com/geordzNZ/FlooringCalculator/blob/e3beb5065c953d095e8691ed1299bff03679eeea/FlooringCalculator/Program.cs#L72-L79
Those could be combined into just one condition that does all the shape specific things

**Comment by incredibleLeitman** [comment]
Also think about if you really need to have all these shape specific variables declared outside of the condition
https://github.com/geordzNZ/FlooringCalculator/blob/e3beb5065c953d095e8691ed1299bff03679eeea/FlooringCalculator/Program.cs#L11-L18

**Comment by geordzNZ** [comment]
Some variables left out as I needed them outside the conditional. but moved what I could (plus noting the other comment about better to use inline declarations

**Comment by geordzNZ** [comment]
Also still assuming the user is competent and can follow instructions and do data entry correct  (at least for now anyways, we all know they mostly arent 😁)
