### ISSUE TITLE
No need to declare Math.Pi as constant

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/FlooringCalculator#6]
https://github.com/geordzNZ/FlooringCalculator/blob/e3beb5065c953d095e8691ed1299bff03679eeea/FlooringCalculator/Program.cs#L7
because it already is: https://learn.microsoft.com/en-us/dotnet/api/system.math.pi?view=net-7.0

**Comment by geordzNZ** [comment]
noted thanks ... think I was trying to simplify the calculation ... but I can see I added an extra line where it wasnt needed.
