### ISSUE TITLE
outdated comment

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/FlooringCalculator#7]
https://github.com/geordzNZ/FlooringCalculator/blob/e3beb5065c953d095e8691ed1299bff03679eeea/FlooringCalculator/Program.cs#L85

This is one of the hardest parts when having comments for code blocks: you need to take care of them whenever you touch the code.
This is one of the main reasons why most developers prefer readable code over comments ^^

**Comment by geordzNZ** [comment]
yep ok, removed now
